"""empty message

Revision ID: a93b99e4ead8
Revises: d033cb1593e1
Create Date: 2018-05-22 15:10:08.107981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a93b99e4ead8'
down_revision = 'd033cb1593e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'somethign')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('somethign', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
